services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: pytorch/pytorch:2.4.0-cuda12.4-cudnn9-runtime
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                # device_ids: ['0']
                capabilities: [compute]
